# Generated by Django 4.2.5 on 2023-11-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(default=False, max_length=13),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='votingapp.election'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
