# Generated by Django 4.2.5 on 2023-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_candidate_bio_vote_election_voter_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
