# Generated by Django 4.2.5 on 2023-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_alter_election_date_alter_election_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(max_length=150, upload_to='candidates/'),
        ),
    ]
